name: Python Application Workflow on macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install build tools for PyQt5
        run: |
          pip install --upgrade pip setuptools wheel
          pip install sip

      - name: Install dependencies
        run: |
          pip install --find-links https://www.riverbankcomputing.com/software/pyqt/download5 PyQt5==5.15.9
          pip install -r requirements.txt

      - name: Install Qt dependencies
        run: brew install qt

      - name: Set Qt environment variables
        run: |
          export QT_QPA_PLATFORM_PLUGIN_PATH=$(brew --prefix qt)/plugins
          export QT_QPA_PLATFORM=cocoa

      - name: Run Python script
        run: python 词性分析最后1.py
