name: Python Application Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    # 检出代码
    - name: Check out code
      uses: actions/checkout@v3

    # 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9  # 指定 Python 版本为 3.9

    # 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel
        pip install -r requirements.txt --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple

    # 测试是否安装成功
    - name: Test PyQt5 installation
      run: |
        python -c "from PyQt5.QtWidgets import QApplication; print('PyQt5 Installed Successfully!')"

    # 打包项目为 macOS 可执行文件
    - name: Package application
      run: |
        pip install pyinstaller -i https://pypi.tuna.tsinghua.edu.cn/simple
        pyinstaller --onefile --windowed 词性分析最后1.py

    # 上传生成的文件作为 Artifact（可选）
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: packaged-application
        path: dist/
