name: Python Application Workflow on macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # macOS 运行环境

    steps:
    # 1. 检出代码
    - name: Check out code
      uses: actions/checkout@v3

    # 2. 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # 根据项目需要设置 Python 版本

    # 3. 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. 运行 Python 脚本
    - name: Run Python script
      run: python 词性分析最后1.py
